services:
  server:
    build:
      target: builder
    volumes:
      - ../../packages:/app/packages:ro
    environment:
      - NODE_ENV=development

  ui:
    build:
      target: builder
    volumes:
      - ../../packages/ui-app:/app/packages/ui-app:ro
    command: ["npx", "vite", "--host", "0.0.0.0", "--port", "8080"]
