// ── Events ── (client event types)

export type ClientEvent =
  | 'connected'
  | 'disconnected'
  | 'reconnecting'
  | 'message'
  | 'message.edited'
  | 'message.deleted'
  | 'dm'
  | 'dm.edited'
  | 'dm.deleted'
  | 'typing'
  | 'presence'
  | 'member.joined'
  | 'member.left'
  | 'member.kicked'
  | 'member.banned'
  | 'channel.created'
  | 'channel.updated'
  | 'channel.deleted'
  | 'role.created'
  | 'role.updated'
  | 'role.deleted'
  | 'community.updated'
  | 'community.info'
  | 'community.list'
  | 'community.auto-joined'
  | 'community.member.updated'
  | 'sync'
  | 'mls.welcome'
  | 'mls.commit'
  | 'mls.keypackage.response'
  | 'voice.joined'
  | 'voice.left'
  | 'voice.state'
  | 'voice.speaking'
  | 'voice.participant.joined'
  | 'voice.participant.left'
  | 'voice.new-producer'
  | 'voice.producer-closed'
  | 'voice.track.published'
  | 'voice.track.removed'
  | 'thread.created'
  | 'thread.message'
  | 'error'
  // Social Recovery
  | 'recovery.request.notify'
  | 'recovery.request.created'
  | 'recovery.request.cancelled'
  | 'recovery.shard.submitted'
  | 'recovery.shards.response'

export type FederationEvent = 'peer.connected' | 'peer.disconnected' | 'peer.message' | 'peer.sync' | 'peer.error'
